### ISSUE TITLE
"#GooglyTank was here <:" request

### ISSUE THREAD

**Issue by GooglyTank** [Zer0-Official/Simpl-Py#4]
**_Can u put "#GooglyTank was here <:" in simpl.py? I will stop calling it simply pie if you do, thank you._**

**Comment by Zer0-Official** [comment]
Let me think about it... if I do add it, it will show up in v-0.8.0-beta

**Comment by GooglyTank** [comment]
Thank you kind sir I will add ur name to my hnefatafl project
