### ISSUE TITLE
Hello, Sorry for the joke issues this one is real though.

### ISSUE THREAD

**Issue by GooglyTank** [Zer0-Official/Simpl-Py#4]
Ok hi so I'm having a problem when I boot the program it crashes then it shows [this](https://bit.ly/3jk9FkV) and im not sure what i mean. I have tried restarting my pc and even reinstalling the entire program with no help. Works fine on my phone from google store but yea! thanks..

**Comment by Zer0-Official** [comment]
please dont spam with ip loggers

**Comment by GooglyTank** [comment]
I dont understand- please explain further dear Vinny
